language: ruby
rvm:
  - 2.0.0

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

cache: bundler

before_script:
  - bundle install

script:
  - bundle exec rake rubocop
  - bundle exec rake test